"""updated emergency request with accepted and donated fields

Revision ID: 0e8d51d9c986
Revises: a42f97f765b5
Create Date: 2024-02-03 00:36:08.028395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8d51d9c986'
down_revision: Union[str, None] = 'a42f97f765b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_requests', sa.Column('accepted', sa.Boolean(), nullable=False))
    op.add_column('emergency_requests', sa.Column('donated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergency_requests', 'donated')
    op.drop_column('emergency_requests', 'accepted')
    # ### end Alembic commands ###
