"""added unique constraint on campaignattendee table

Revision ID: 0e976d5c2f90
Revises: 4cfd52a0221c
Create Date: 2024-02-05 20:13:08.471677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e976d5c2f90'
down_revision: Union[str, None] = '4cfd52a0221c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campaign_attendees_campaign_id_key',
                       'campaign_attendees', type_='unique')
    op.drop_constraint('campaign_attendees_donor_id_key',
                       'campaign_attendees', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'campaign_attendees_donor_id_key', 'campaign_attendees', ['donor_id'])
    op.create_unique_constraint(
        'campaign_attendees_campaign_id_key', 'campaign_attendees', ['campaign_id'])
    # ### end Alembic commands ###
