"""add referene to donor and hopital in user table

Revision ID: 1a12d0299a77
Revises: 1aa7f23fad2f
Create Date: 2024-01-28 03:00:23.387646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a12d0299a77'
down_revision: Union[str, None] = '1aa7f23fad2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('donor_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'hospitals', ['hospital_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'donors', ['donor_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'hospital_id')
    op.drop_column('users', 'donor_id')
    # ### end Alembic commands ###
