"""auto generate donors and hospitals with points, city and last donation date

Revision ID: 1aa7f23fad2f
Revises: 47d5dceab050
Create Date: 2024-01-28 02:02:00.794028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa7f23fad2f'
down_revision: Union[str, None] = '47d5dceab050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('city', sa.String(), nullable=False))
    op.add_column('donors', sa.Column('last_donation_date', sa.DateTime(), nullable=True))
    op.add_column('donors', sa.Column('points', sa.Integer(), nullable=False))
    op.add_column('hospitals', sa.Column('city', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'city')
    op.drop_column('donors', 'points')
    op.drop_column('donors', 'last_donation_date')
    op.drop_column('donors', 'city')
    # ### end Alembic commands ###
