"""drop password column from donor and hospital table

Revision ID: 207e4997b1ad
Revises: f68e9d5ba0a2
Create Date: 2023-12-25 16:33:34.970322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207e4997b1ad'
down_revision: Union[str, None] = 'f68e9d5ba0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donors', 'password')
    op.drop_column('hospitals', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('donors', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
