"""add image filed

Revision ID: 47d5dceab050
Revises: 579458891610
Create Date: 2023-12-31 13:44:37.451812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d5dceab050'
down_revision: Union[str, None] = '579458891610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('image', sa.String(), nullable=False))
    op.add_column('hospitals', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'image')
    op.drop_column('donors', 'image')
    # ### end Alembic commands ###
