"""add emergency request table

Revision ID: 5658ecdf5822
Revises: 1a12d0299a77
Create Date: 2024-02-02 02:05:28.715275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5658ecdf5822'
down_revision: Union[str, None] = '1a12d0299a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_requests',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('patient_name', sa.String(), nullable=False),
                    sa.Column('blood_group', sa.String(), nullable=False),
                    sa.Column('medical_condition',
                              sa.String(), nullable=False),
                    sa.Column('report', sa.String(), nullable=False),
                    sa.Column('requested_time', sa.DateTime(), nullable=False),
                    sa.Column('expiry_time', sa.DateTime(), nullable=False),
                    sa.Column('donor_id', sa.Integer(), nullable=True),
                    sa.Column('hospital_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
                    sa.ForeignKeyConstraint(
                        ['hospital_id'], ['hospitals.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_requests')
    # ### end Alembic commands ###
