"""add latitude and longitude fields

Revision ID: 579458891610
Revises: 91d158b0b55e
Create Date: 2023-12-31 01:27:47.259047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579458891610'
down_revision: Union[str, None] = '91d158b0b55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('latitude', sa.Double(), nullable=False))
    op.add_column('donors', sa.Column('longitude', sa.Double(), nullable=False))
    op.add_column('hospitals', sa.Column('latitude', sa.Double(), nullable=False))
    op.add_column('hospitals', sa.Column('longitude', sa.Double(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'longitude')
    op.drop_column('hospitals', 'latitude')
    op.drop_column('donors', 'longitude')
    op.drop_column('donors', 'latitude')
    # ### end Alembic commands ###
