"""added campaign attendee table

Revision ID: 7ec6bb5b1275
Revises: 0e8d51d9c986
Create Date: 2024-02-05 15:37:24.623040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec6bb5b1275'
down_revision: Union[str, None] = '0e8d51d9c986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
