"""add unique constraint on campaign attende table

Revision ID: bb77484faeca
Revises: 4cfd52a0221c
Create Date: 2024-02-05 18:01:03.521380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb77484faeca'
down_revision: Union[str, None] = '4cfd52a0221c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_attendees',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('donor_id', sa.Integer(), nullable=True),
                    sa.Column('campaign_id', sa.Integer(), nullable=True),
                    sa.Column('donated', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['campaign_id'], ['campaigns.id'], ),
                    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('donor_id', 'campaign_id',
                                        name='_donor_campaign_uc')
                    )
    op.create_index(op.f('ix_campaign_attendees_id'),
                    'campaign_attendees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_attendees_id'),
                  table_name='campaign_attendees')
    op.drop_table('campaign_attendees')
    # ### end Alembic commands ###
