"""auto generate tables

Revision ID: f5a7e23af643
Revises: 2b40e5688c2f
Create Date: 2023-12-24 21:51:03.509594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5a7e23af643'
down_revision: Union[str, None] = '2b40e5688c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(length=10), nullable=False),
                    sa.Column('blood_group', sa.String(), nullable=False),
                    sa.Column('sex', sa.CHAR(), nullable=False),
                    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_donors_email'), 'donors', ['email'], unique=True)
    op.create_index(op.f('ix_donors_id'), 'donors', ['id'], unique=False)
    op.create_index(op.f('ix_donors_phone'), 'donors', ['phone'], unique=True)
    op.create_table('hospitals',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(length=10), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('NOW()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_hospitals_email'),
                    'hospitals', ['email'], unique=True)
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_phone'),
                    'hospitals', ['phone'], unique=True)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('is_donor', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('password_reset_tokens', 'expiry_time',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.TIMESTAMP(timezone=True),
                    existing_nullable=False,
                    existing_server_default=sa.text("(now() + '00:05:00'::interval)"))
    op.drop_index('ix_password_reset_tokens_user_email',
                  table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_user_email'),
                    'password_reset_tokens', ['user_email'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_otp'),
                    'password_reset_tokens', ['otp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_otp'),
                  table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_email'),
                  table_name='password_reset_tokens')
    op.create_index('ix_password_reset_tokens_user_email',
                    'password_reset_tokens', ['user_email'], unique=False)
    op.alter_column('password_reset_tokens', 'expiry_time',
                    existing_type=sa.TIMESTAMP(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False,
                    existing_server_default=sa.text("(now() + '00:05:00'::interval)"))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospitals_phone'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_email'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_donors_phone'), table_name='donors')
    op.drop_index(op.f('ix_donors_id'), table_name='donors')
    op.drop_index(op.f('ix_donors_email'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
