"""Recreate tables

Revision ID: f68e9d5ba0a2
Revises: f5a7e23af643
Create Date: 2023-12-25 15:33:22.265674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68e9d5ba0a2'
down_revision: Union[str, None] = 'f5a7e23af643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=False),
    sa.Column('sex', sa.CHAR(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_email'), 'donors', ['email'], unique=True)
    op.create_index(op.f('ix_donors_id'), 'donors', ['id'], unique=False)
    op.create_index(op.f('ix_donors_phone'), 'donors', ['phone'], unique=True)
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_email'), 'hospitals', ['email'], unique=True)
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_phone'), 'hospitals', ['phone'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('expiry_time', sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW() + INTERVAL '5 minutes'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_otp'), 'password_reset_tokens', ['otp'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_email'), 'password_reset_tokens', ['user_email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_donor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_password_reset_tokens_user_email'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_otp'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_hospitals_phone'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_email'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_donors_phone'), table_name='donors')
    op.drop_index(op.f('ix_donors_id'), table_name='donors')
    op.drop_index(op.f('ix_donors_email'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
